# Generated by Django 4.2.4 on 2023-09-11 18:48

from django.db import migrations, models
import prize.models
import user_data.models


class Migration(migrations.Migration):

    dependencies = [
        ('prize', '0018_rename_redeemedprizes_userredeemedprizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prizes',
            name='logo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=prize.models.get_upload_path_logos, validators=[user_data.models.validate_image_size]),
        ),
    ]
