# Generated by Django 4.2.4 on 2023-09-11 18:48

from django.db import migrations, models
import user_data.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0014_alter_customuser_options_alter_history_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=user_data.models.get_upload_path_users, validators=[user_data.models.validate_image_size]),
        ),
    ]
